// DMLDemo1.dmlInsertDemo_stndObj();
// DMLDemo1.dmlInsertDemo_cstmObj();

//SoqlSampleDemo3.accountParentToChild3();
//Assigments30 assig = new Assigments30();
//Assigments30.Assigments30('Channel - Direct');

DMLDemo1.dmlInsertDemo_cstmObj();
DMLDemo1.dmlInsertDemo1_stndObj();
DMLDemo1.dmlUpdateDemo3();
DMLDemo1.dmlUpdateDemo2();

AssigmentOct31. AssigmentsDML('Sunday fun');
account acc2=[select id from account where name='ali' limit 1];
AssigmentOct31. AssigmentsDML(acc2);